name: 1.2.3.$(rev:rrr)

trigger:
- master

schedules:
- cron: 0 5 * * 6
  branches:
    include:
    - master
  always: true

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  lfs: true
- task: UseDotNet@2
  inputs:
    version: 6.0.x
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)\XNAControls.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)\XNAControls.sln'
    arguments: '--configuration $(buildConfiguration)'
    versioningScheme: byBuildNumber
- task: DotNetCoreCLI@2
  displayName: 'Run tests - disabled (not supported on hosted agent, need graphics device)'
  condition: false
  inputs:
    command: 'test'
    projects: '$(Build.SourcesDirectory)\XNAControls.sln'
- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)\XNAControls\bin\$(buildConfiguration)
    TargetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
